
name: One-Click Build & Publish APK
on:
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with: { distribution: 'temurin', java-version: '17' }
      - uses: android-actions/setup-android@v3
      - run: |
          yes | sdkmanager --licenses
          sdkmanager "platform-tools" "platforms;android-34" "build-tools;34.0.0"
      - run: ./gradlew --no-daemon assembleDebug
      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with: { name: app-debug-apk, path: app/build/outputs/apk/debug/app-debug.apk }
      - name: Create GitHub Release
        uses: ncipollo/release-action@v1
        with:
          tag: "apk-${{ github.run_number }}"
          name: "APK ${{ github.run_number }}"
          draft: false
          prerelease: false
          artifacts: "app/build/outputs/apk/debug/app-debug.apk"
